# version: 0.2
# env:
#   variables:
#     AWS_REGION: us-east-2
#     FRONTEND_S3_BUCKET: taskmgr-frontend-deploy
#     REACT_APP_API_URL: https://<api-gateway-id>.execute-api.us-east-2.amazonaws.com/prod
# phases:
#   install:
#     runtime-versions:
#       nodejs: 18
#     commands:
#       - npm ci
#   build:
#     commands:
#       - echo "Building React app..."
#       - npm run build
#       - echo "Deploying to S3..."
#       - aws s3 sync build/ s3://$FRONTEND_S3_BUCKET --delete
# artifacts:
#   files:
#     - build/**/*
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building frontend...
      - npm run build
  post_build:
    commands:
      - echo Syncing build to S3...
      - aws s3 sync build/ s3://aws-task-manager-frontend --delete
artifacts:
  files:
    - '**/*'
  base-directory: build

